### ISSUE TITLE
Is it possible to copy the URL of a feed to the clipboard?

### ISSUE THREAD

**Issue by Lo-lo78** [nvdaes/readFeeds#11]
Hi Noelia,
you can put a button in the dialog box that copies the URL of the selected feed to the clipboard.
Very useful if you need to quickly share a feed.
Thanks for everything you do!

**Comment by nvdaes** [comment]
Thanks for the suggestion. I will try to add it.

**Comment by nvdaes** [comment]
Hi @Lo-lo78, please  test this new dev version, where I have addedd the requested button to copy the feed address. It's placed after the Open as HTML button in the feeds dialog:

https://github.com/nvdaes/readFeeds/releases/download/10.12-dev/readFeeds-10.12-dev.nvda-addon

Feel free to reopen this issue or create another one if you have more suggestions.
Thanks
