### ISSUE TITLE
[Bug]: Removes shortcuts for other items in Tools

### ISSUE THREAD

**Issue by SamKacer** [nvdaes/readFeeds#20]
### Summary

Other items in Tools menu with R as shortcut, lose this shortcut when this addon is enabled.

### To reproduce

1. Open NVDA menu, then Tools
2. Press R

### Expected behavior

These two items should also have the R key as a shortcut for english:

1. Run COM Registration Fixing tool...
2. Reload plugins

### Version

11.3

**Comment by nvdaes** [comment]
Thanks, @SamKacer .
This seems to be fixed in PR #21 .
Hopely I can merge it soon. Feel free to provide feedback if needed.

**Comment by SamKacer** [comment]
nice, good job on such a quick fix :)
